### ISSUE TITLE
I would like to maintain prebuilt kernels for Fedora.

### ISSUE THREAD

**Issue by daeSundae** [amonet-kamakiri/prebuilt-kernels#2]
Hi, it's me again. To maybe possibly help to other fedora users like me out there i would like to commit patched prebuilt kernels for every fedora release here. I'm using Fedora 33 right now but i can compile one for Fedora 34 as well whenever it gets stable release. I just would like to know, how do you make the prebuilt kernels? Do you use default configs? 
I've checked google a bit but couldn't find a guide for it or couldnt find something that would tell me how it would work.

**Comment by chaosmaster** [comment]
I had already linked you to the fedora wiki in your [other issue](https://github.com/amonet-kamakiri/prebuilt-kernels/issues/1#issuecomment-797658580).
Since I don't use fedora, I'm not sure how to help you with that.
The other kernels are built according to the distros documentations, the only addition being the usb-patch.

**Comment by daeSundae** [comment]
I mean i have no problems compiling, i was just wondering what config did you use (default menuconfig?) to build the kernels?

**Comment by chaosmaster** [comment]
The distros default configs.
